# Generated by Django 5.1.1 on 2024-09-04 21:17

from django.db import migrations


def populate_status(apps, schemaeditor): #a python function
    entries = {
        "to do": "An issue waiting to be worked on",
        "in progress": "An issue being worked on",
        "done": "An issue completed"
    }

    Status = apps.get_model("issues", "Status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
